export { default as MainPage } from './main'
export { default as SignUpPage } from './sign-up'
export { default as LogInPage } from './log-in'
export { default as DashboardPage } from './dashboard'
export { default as TodosPage } from './todos'
